# Generated by Django 6.0.7 on 2026-08-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_ubicacion_pais_fk_destino_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ubicacion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("planta", "Planta"),
                    ("puerto", "Puerto"),
                    ("aeropuerto", "Aeropuerto"),
                    ("cliente", "Cliente"),
                    ("expreso", "Expreso"),
                    ("otro", "Otro"),
                ],
                default="cliente",
                max_length=20,
            ),
        ),
    ]
