# Generated by Django 6.0.7 on 2026-08-12 14:28

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_alter_ubicacion_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Provincia",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("nombre", models.CharField(max_length=80)),
                ("superficie_km2", models.DecimalField(decimal_places=4, max_digits=12)),
                ("geom", django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ("geom_display", django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ("codigo", models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "provincia",
                "verbose_name_plural": "provincias",
                "db_table": "provincia",
                "ordering": ["nombre"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Departamento",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("nombre", models.CharField(max_length=80)),
                ("superficie_km2", models.DecimalField(decimal_places=4, max_digits=12)),
                ("geom", django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ("geom_display", django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ("codigo", models.CharField(max_length=5, primary_key=True, serialize=False)),
                (
                    "provincia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="departamentos",
                        to="catalog.provincia",
                    ),
                ),
            ],
            options={
                "verbose_name": "departamento",
                "verbose_name_plural": "departamentos",
                "db_table": "departamento",
                "ordering": ["nombre"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
