# Generated by Django 6.0.7 on 2026-08-12 18:26

import catalog.db_functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_zona_multipolygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='superficie_km2',
            field=models.GeneratedField(db_persist=True, expression=catalog.db_functions.SuperficieKm2('geom'), output_field=models.DecimalField(decimal_places=4, max_digits=12)),
        ),
    ]
