# Generated by Django 6.0.7 on 2026-08-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_ordenservicio_hombreador_ordenservicio_tipo_camion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='fecha_viaje',
            field=models.DateField(blank=True, null=True),
        ),
    ]
