# Generated by Django 6.0.7 on 2026-08-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0004_ordenservicio_tipo_operacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='via',
            field=models.CharField(choices=[('aerea', 'Aerea'), ('maritima', 'Maritima'), ('terrestre', 'Terrestre')], default='terrestre', max_length=20),
        ),
    ]
