# Generated by Django 6.0.7 on 2026-08-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistica", "0005_ordenservicio_via"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordenservicio",
            name="facturable",
            field=models.BooleanField(default=False),
        ),
    ]
