# Generated by Django 6.0.7 on 2026-08-10 16:13

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_alter_ubicacion_tipo"),
        ("logistica", "0006_ordenservicio_facturable"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdenServicioDestino",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("secuencia", models.PositiveSmallIntegerField(default=0)),
                (
                    "orden_servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinos",
                        to="logistica.ordenservicio",
                    ),
                ),
                (
                    "ubicacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes_servicio_destino",
                        to="catalog.ubicacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden Servicio Destino",
                "verbose_name_plural": "Ordenes Servicio Destino",
                "db_table": "orden_servicio_destino",
                "abstract": False,
                "base_manager_name": "all_objects",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("active", True)),
                        fields=("orden_servicio", "ubicacion"),
                        name="uq_orden_servicio_destino_active",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
