# Generated by Django 6.0.7 on 2026-08-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0007_ordenserviciodestino'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='modalidad',
            field=models.CharField(blank=True, choices=[('directo', 'Directo'), ('multiparada', 'Multiparada')], max_length=20, null=True),
        ),
    ]
