# Generated by Django 6.0.7 on 2026-08-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0008_ordenservicio_modalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='costo_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
    ]
