# Generated by Django 6.0.7 on 2026-07-31 19:51

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remito',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=13)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('orden_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remitos', to='logistica.ordenservicio')),
            ],
            options={
                'verbose_name': 'Remito',
                'verbose_name_plural': 'Remitos',
                'db_table': 'remito',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RemitoDestino',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('remito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='tracking.remito')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remitos_destino', to='catalog.ubicacion')),
            ],
            options={
                'verbose_name': 'Remito Destino',
                'verbose_name_plural': 'Remitos Destino',
                'db_table': 'remito_destino',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateTimeField()),
                ('fecha_egreso', models.DateTimeField(blank=True, null=True)),
                ('orden_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='logistica.ordenservicio')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='catalog.ubicacion')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'ticket',
                'ordering': ['-fecha_ingreso'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='remito',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('numero',), name='uq_remito_numero_active'),
        ),
        migrations.AddConstraint(
            model_name='remitodestino',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('remito', 'ubicacion'), name='uq_remito_destino_active'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('numero', 'planta'), name='uq_ticket_numero_planta_active'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_egreso__isnull', True), ('fecha_egreso__gte', models.F('fecha_ingreso')), _connector='OR'), name='ck_ticket_egreso_posterior_a_ingreso'),
        ),
    ]
