# Generated by Django 6.0.7 on 2026-08-07 12:54

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_ubicacion_pais_fk_destino_default'),
        ('logistica', '0006_ordenservicio_facturable'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        # Va primero: sin la extension, gin_trgm_ops no existe y los AddIndex fallan.
        # CREATE EXTENSION pide superuser; donde el usuario de la app no lo sea, la crea un DBA.
        TrigramExtension(),
        migrations.AddIndex(
            model_name='remito',
            index=django.contrib.postgres.indexes.GinIndex(fields=['numero'], name='idx_remito_numero_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=django.contrib.postgres.indexes.GinIndex(fields=['numero'], name='idx_ticket_numero_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
