# Generated by Django 6.0.7 on 2026-08-14 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistica", "0009_ordenservicio_costo_real_ordenservicio_observaciones"),
        ("tracking", "0002_remito_idx_remito_numero_trgm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="orden_servicio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="logistica.ordenservicio",
            ),
        ),
    ]
