# Generated by Django 6.0.7 on 2026-07-31 19:51

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transportista",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("cuit", models.CharField(max_length=13)),
                ("razon_social", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "transportista",
                "verbose_name_plural": "transportistas",
                "db_table": "transportista",
                "abstract": False,
                "base_manager_name": "all_objects",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("active", True)),
                        fields=("cuit",),
                        name="uq_carrier_active_cuit",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
