# Generated by Django 6.0.7 on 2026-08-03 16:19

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_alter_zona_options_alter_zona_geom_and_more"),
        ("transportista", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptoAdicional",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("codigo", models.CharField(max_length=20)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "unidad",
                    models.CharField(choices=[("dia", "Dia"), ("hora", "Hora")], max_length=20),
                ),
            ],
            options={
                "verbose_name": "Concepto Adicional",
                "verbose_name_plural": "Conceptos Adicionales",
                "db_table": "concepto_adicional",
                "ordering": ["codigo"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("active", True)),
                        fields=("codigo",),
                        name="uq_concepto_adicional_codigo",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Tarifario",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("vigente_desde", models.DateField()),
                ("vigente_hasta", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[("vigente", "Vigente"), ("cerrado", "Cerrado")],
                        default="vigente",
                        max_length=20,
                    ),
                ),
                (
                    "transportista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tarifarios",
                        to="transportista.transportista",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarifario",
                "verbose_name_plural": "Tarifarios",
                "db_table": "tarifario",
                "ordering": ["-vigente_desde"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="TarifaFlete",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "modalidad",
                    models.CharField(
                        choices=[("directo", "Directo"), ("multiparada", "Multiparada")],
                        max_length=20,
                    ),
                ),
                (
                    "tipo_camion",
                    models.CharField(
                        choices=[("chasis", "Chasis"), ("balancin", "Balancin"), ("semi", "Semi")],
                        max_length=20,
                    ),
                ),
                ("hombreador", models.BooleanField(default=False)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "ubicacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tarifas_flete",
                        to="catalog.ubicacion",
                    ),
                ),
                (
                    "zona",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tarifas_flete",
                        to="catalog.zona",
                    ),
                ),
                (
                    "tarifario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifas_flete",
                        to="transportista.tarifario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarifa de Flete",
                "verbose_name_plural": "Tarifas de Flete",
                "db_table": "tarifa_flete",
                "ordering": ["modalidad", "tipo_camion"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="TarifaConceptoAdicional",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tarifas_conceptos",
                        to="transportista.conceptoadicional",
                    ),
                ),
                (
                    "tarifario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifas_conceptos",
                        to="transportista.tarifario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarifa de Concepto Adicional",
                "verbose_name_plural": "Tarifas de Conceptos Adicionales",
                "db_table": "tarifa_concepto_adicional",
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="tarifario",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True), ("estado", "vigente")),
                fields=("transportista",),
                name="uq_tarifario_transpo_vig",
            ),
        ),
        migrations.AddConstraint(
            model_name="tarifaflete",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("ubicacion__isnull", True), ("zona__isnull", False)),
                    models.Q(("ubicacion__isnull", False), ("zona__isnull", True)),
                    _connector="OR",
                ),
                name="ck_tarifa_flete_zona_xor_ubicacion",
            ),
        ),
        migrations.AddConstraint(
            model_name="tarifaflete",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True), ("zona__isnull", False)),
                fields=("tarifario", "zona", "modalidad", "tipo_camion", "hombreador"),
                name="uq_tarifa_flete_zona",
            ),
        ),
        migrations.AddConstraint(
            model_name="tarifaflete",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True), ("ubicacion__isnull", False)),
                fields=("tarifario", "ubicacion", "modalidad", "tipo_camion", "hombreador"),
                name="uq_tarifa_flete_ubicacion",
            ),
        ),
        migrations.AddConstraint(
            model_name="tarifaconceptoadicional",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("tarifario", "concepto"),
                name="uq_tarifa_concepto",
            ),
        ),
    ]
