/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedOrdenesServicioRouteImport } from './routes/_authenticated/ordenes-servicio'
import { Route as AuthenticatedTarifariosRouteImport } from './routes/_authenticated/tarifarios'
import { Route as AuthenticatedUbicacionesRouteImport } from './routes/_authenticated/ubicaciones'
import { Route as AuthenticatedZonasRouteImport } from './routes/_authenticated/zonas'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdenesServicioRoute =
  AuthenticatedOrdenesServicioRouteImport.update({
    id: '/ordenes-servicio',
    path: '/ordenes-servicio',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTarifariosRoute = AuthenticatedTarifariosRouteImport.update({
  id: '/tarifarios',
  path: '/tarifarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUbicacionesRoute =
  AuthenticatedUbicacionesRouteImport.update({
    id: '/ubicaciones',
    path: '/ubicaciones',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedZonasRoute = AuthenticatedZonasRouteImport.update({
  id: '/zonas',
  path: '/zonas',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/ordenes-servicio': typeof AuthenticatedOrdenesServicioRoute
  '/tarifarios': typeof AuthenticatedTarifariosRoute
  '/ubicaciones': typeof AuthenticatedUbicacionesRoute
  '/zonas': typeof AuthenticatedZonasRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/ordenes-servicio': typeof AuthenticatedOrdenesServicioRoute
  '/tarifarios': typeof AuthenticatedTarifariosRoute
  '/ubicaciones': typeof AuthenticatedUbicacionesRoute
  '/zonas': typeof AuthenticatedZonasRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/ordenes-servicio': typeof AuthenticatedOrdenesServicioRoute
  '/_authenticated/tarifarios': typeof AuthenticatedTarifariosRoute
  '/_authenticated/ubicaciones': typeof AuthenticatedUbicacionesRoute
  '/_authenticated/zonas': typeof AuthenticatedZonasRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ordenes-servicio'
    | '/tarifarios'
    | '/ubicaciones'
    | '/zonas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/ordenes-servicio'
    | '/tarifarios'
    | '/ubicaciones'
    | '/zonas'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/ordenes-servicio'
    | '/_authenticated/tarifarios'
    | '/_authenticated/ubicaciones'
    | '/_authenticated/zonas'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ordenes-servicio': {
      id: '/_authenticated/ordenes-servicio'
      path: '/ordenes-servicio'
      fullPath: '/ordenes-servicio'
      preLoaderRoute: typeof AuthenticatedOrdenesServicioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tarifarios': {
      id: '/_authenticated/tarifarios'
      path: '/tarifarios'
      fullPath: '/tarifarios'
      preLoaderRoute: typeof AuthenticatedTarifariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ubicaciones': {
      id: '/_authenticated/ubicaciones'
      path: '/ubicaciones'
      fullPath: '/ubicaciones'
      preLoaderRoute: typeof AuthenticatedUbicacionesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/zonas': {
      id: '/_authenticated/zonas'
      path: '/zonas'
      fullPath: '/zonas'
      preLoaderRoute: typeof AuthenticatedZonasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedOrdenesServicioRoute: typeof AuthenticatedOrdenesServicioRoute
  AuthenticatedTarifariosRoute: typeof AuthenticatedTarifariosRoute
  AuthenticatedUbicacionesRoute: typeof AuthenticatedUbicacionesRoute
  AuthenticatedZonasRoute: typeof AuthenticatedZonasRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedOrdenesServicioRoute: AuthenticatedOrdenesServicioRoute,
  AuthenticatedTarifariosRoute: AuthenticatedTarifariosRoute,
  AuthenticatedUbicacionesRoute: AuthenticatedUbicacionesRoute,
  AuthenticatedZonasRoute: AuthenticatedZonasRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
