# Generated by Django 6.0.7 on 2026-08-05 15:13

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
                'db_table': 'rol',
                'ordering': ['nombre'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(choices=[('zonas.ver', 'zonas.ver'), ('zonas.crear', 'zonas.crear'), ('zonas.editar', 'zonas.editar')], max_length=60)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'permiso',
                'verbose_name_plural': 'permisos',
                'db_table': 'permiso',
                'ordering': ['codigo'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('codigo',), name='uq_permiso_codigo_active')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_permisos', to='users.permiso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_permisos', to='users.rol')),
            ],
            options={
                'verbose_name': 'permiso del rol',
                'verbose_name_plural': 'permisos del rol',
                'db_table': 'rol_permiso',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(blank=True, related_name='roles', through='users.RolPermiso', to='users.permiso'),
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_roles', to='users.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'rol del usuario',
                'verbose_name_plural': 'roles del usuario',
                'db_table': 'usuario_rol',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='usuarios', through='users.UsuarioRol', to='users.rol'),
        ),
        migrations.AddConstraint(
            model_name='rolpermiso',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('rol', 'permiso'), name='uq_rol_permiso_active'),
        ),
        migrations.AddConstraint(
            model_name='rol',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('nombre',), name='uq_rol_nombre_active'),
        ),
        migrations.AddConstraint(
            model_name='usuariorol',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('usuario', 'rol'), name='uq_usuario_rol_active'),
        ),
    ]
