# Generated by Django 6.0.7 on 2026-08-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_permiso_codigo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permiso",
            name="codigo",
            field=models.CharField(
                choices=[
                    ("zonas.ver", "zonas.ver"),
                    ("zonas.crear", "zonas.crear"),
                    ("zonas.editar", "zonas.editar"),
                    ("zonas.eliminar", "zonas.eliminar"),
                    ("ubicaciones.ver", "ubicaciones.ver"),
                    ("ubicaciones.editar", "ubicaciones.editar"),
                    ("ordenes_servicio.ver", "ordenes_servicio.ver"),
                    ("ordenes_servicio.editar", "ordenes_servicio.editar"),
                    ("ordenes_servicio.calcular_costo", "ordenes_servicio.calcular_costo"),
                ],
                max_length=60,
            ),
        ),
    ]
